### ISSUE TITLE
question

### ISSUE THREAD

**Issue by OutBoundMan** [Travus/CommentSniper#1]
Is it possible to create a program like this: https://youtu.be/HcVa3LfG59E

Can you email me iamoutbound@gmail.com ?

**Comment by Travus** [comment]
I'm sure something like this would somehow be possible, especially the comment spam would likely be relatively simple to implement.

However;
1) This would go against YouTube's guidelines.
2) My program is there to help combat things like this, I don't want to add to the problem.

As such, I must decline in helping you with this. Sorry.
